compressionLevel: 0
enableGlobalCache: false
enableScripts: false
enableTelemetry: false
globalFolder: "../.yarn/berry" # Workaround for 'EXDEV: cross-device link not permitted' errors on GHA
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
  - code: YN0068 # Ignore `packageExtensions` set by root project
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
dynamicPackageExtensions: false
tsEnableAutoTypes: false
yarnPath: ../.yarn/releases/yarn-4.6.0.cjs
