enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
  - code: YN0068 # Ignore `packageExtensions` set by root project
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  "@algolia/autocomplete-core@^1.9":
    peerDependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
      algoliasearch: ">= 4.9.1 < 6"
      search-insights: ">= 1 < 3"
  "@algolia/autocomplete-plugin-algolia-insights@^1.9":
    peerDependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
      algoliasearch: ">= 4.9.1 < 6"
  "@docsearch/react@^3.5":
    dependencies:
      "@algolia/client-search": "^4.19.1"
  "@docusaurus/core@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-content-blog@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-content-docs@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-content-pages@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-debug@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-google-analytics@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-google-gtag@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-google-tag-manager@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/plugin-sitemap@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/preset-classic@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/theme-classic@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/theme-common@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  "@docusaurus/theme-search-algolia@^3.0":
    peerDependencies:
      typescript: ">= 2.7"
  react-dev-utils@^12.0:
    peerDependencies:
      typescript: ">= 2.7"
      webpack: ">= 4"
yarnPath: ../.yarn/releases/yarn-3.8.0.cjs
