name: Yarn
description: Runs `yarn install` and caches downloaded dependencies
inputs:
  working-directory:
    description: The working directory to use when running yarn
    type: string

runs:
  using: composite
  steps:
    - name: Install package dependencies
      run: yarn ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CI_SKIP_GO: 1
