name: Yarn
description: Runs `yarn install` and caches downloaded dependencies

runs:
  using: composite
  steps:
    - name: Install package dependencies
      run: yarn ci
      shell: bash
      env:
        CI_SKIP_GO: 1
