compressionLevel: 0

dynamicPackageExtensions: ./scripts/dependencies.config.js

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

externalWorkspacesOutputPath: .

globalFolder: .yarn/berry

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0069
    level: error

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@react-native/codegen@*":
    dependencies:
      "@babel/core": ^7.20.0
      "@babel/parser": ^7.20.0
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  metro-config@*:
    dependencies:
      metro-transform-worker: ^0.83.1
  react-native-macos@0.78:
    dependencies:
      "@react-native-community/cli": ^15.0.1
      "@react-native-community/cli-platform-apple": ^15.0.1
      "@react-native-community/cli-platform-ios": ^15.0.1
  react-native@*:
    dependencies:
      "@react-native-community/cli": ^18.0.0
  recast@*:
    dependencies:
      "@babel/parser": ^7.20.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - path: incubator/yarn-plugin-dynamic-extensions/index.js
  - path: incubator/yarn-plugin-external-workspaces/dist/external-workspaces.cjs
  - path: incubator/yarn-plugin-install-to/dist/yarn-plugin-install-to.cjs

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.10.3.cjs
