compressionLevel: 0

dynamicPackageExtensions: ./scripts/dependencies.config.js

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

externalWorkspacesOutputPath: test-repos

globalFolder: .yarn/berry # Workaround for 'EXDEV: cross-device link not permitted' errors on GHA

logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
  - code: YN0069 # This rule seems redundant when applied on the original package
    level: error

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      # https://github.com/microsoft/fluentui/pull/30964
      "@types/react":
        optional: true
  "@react-native/dev-middleware@*":
    dependencies:
      # https://github.com/facebook/react-native/pull/49047
      invariant: ^2.2.4
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  metro-config@*:
    dependencies:
      # `metro-config` fails to resolve `JsTransformerConfig` because it's in another package
      metro-transform-worker: ^0.81.0
  react-native@*:
    dependencies:
      # https://github.com/facebook/react-native/pull/47304
      "@react-native-community/cli": ^15.0.0
      # https://github.com/facebook/react-native/pull/47308
      "@react-native-community/cli-platform-android": ^15.0.0
      "@react-native-community/cli-platform-ios": ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - path: incubator/yarn-plugin-dynamic-extensions/index.js
  - path: .yarn/plugins/@rnx-kit/yarn-plugin-external-workspaces.cjs
    spec: incubator/yarn-plugin-external-workspaces/dist/external-workspaces.cjs

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
