enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
nodeLinker: pnpm
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@microsoft/eslint-plugin-sdl@0.x":
    peerDependencies:
      eslint: ">=5.16.0"
  "@react-native-community/cli-debugger-ui@*":
    dependencies:
      "@babel/runtime": "^7.20.0"
  "@react-native/codegen@*":
    dependencies:
      glob: "^7.1.1"
      invariant: "^2.2.4"
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  memfs@4.x:
    peerDependenciesMeta:
      memfs:
        optional: true
      quill-delta:
        optional: true
      rxjs:
        optional: true
      tslib:
        optional: true
  metro-config@*:
    dependencies:
      # `metro-config` fails to resolve `JsTransformerConfig` because it's in another package
      metro-transform-worker: "^0.76.5"
  metro-transform-worker@*:
    dependencies:
      # `metro` has this dependency, but it's being resolved from `metro-transform-worker`
      metro-minify-terser: "^0.76.5"
  react-native-macos@*:
    dependencies:
      # These two are required by `react-native-macos/local-cli/runMacOS/runMacOS.js`
      "@react-native-community/cli-tools": "^11.3.6"
      chalk: "^4.1.0"
    peerDependencies:
      "@babel/preset-env": ^7.1.6
      react-native: "*"
  react-native-windows@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@*:
    dependencies:
      # Implicit dependency introduced by Babel
      "@babel/runtime": "^7.20.0"
    peerDependencies:
      "@babel/preset-env": ^7.1.6
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
yarnPath: .yarn/releases/yarn-3.6.1.cjs
