enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@microsoft/eslint-plugin-sdl@0.x":
    peerDependencies:
      eslint: ">=5.16.0"
  "babel-plugin-transform-flow-enums@*":
    peerDependencies:
      "@babel/core": ^7.20.0
  "memfs@4.x":
    peerDependenciesMeta:
      "quill-delta":
        optional: true
      "memfs":
        optional: true
      "rxjs":
        optional: true
      "tslib":
        optional: true
  "metro-transform-worker@*":
    dependencies:
      "metro-minify-terser": "0.76.8"
  "react-native@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  "react-native-macos@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
      "react-native": "*"
  "react-native-windows@*":
    peerDependencies:
      "@babel/preset-env": ^7.1.6
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
yarnPath: .yarn/releases/yarn-3.6.1.cjs
