compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

externalWorkspacesOutputPath: test-repos

globalFolder: .yarn/berry

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0069
    level: error

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@react-native/dev-middleware@*":
    dependencies:
      invariant: ^2.2.4
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  metro-config@*:
    dependencies:
      metro-transform-worker: ^0.81.0
  react-native@*:
    dependencies:
      "@react-native-community/cli": ^15.0.0
      "@react-native-community/cli-platform-android": ^15.0.0
      "@react-native-community/cli-platform-ios": ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - checksum: f82173c1d7272a10ff5150dcde56088c5edb37db0e9699c3edb894e76997cc6893f2e665d4c797654f412689d06b22c0cdfa80acf45ba7b86bdd2f281e9ffe33
    path: .yarn/plugins/@rnx-kit/yarn-plugin-external-workspaces.cjs
    spec: incubator/yarn-plugin-external-workspaces/dist/external-workspaces.cjs

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
