compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

globalFolder: .yarn/berry

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0069
    level: error

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@react-native/dev-middleware@*":
    dependencies:
      invariant: ^2.2.4
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  metro-config@*:
    dependencies:
      metro-transform-worker: ^0.81.0
  react-native@*:
    dependencies:
      "@react-native-community/cli": ^15.0.0
      "@react-native-community/cli-platform-android": ^15.0.0
      "@react-native-community/cli-platform-ios": ^15.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - checksum: da32bb68893a8e3ebaf031b6d81385b1d3ddd03f8fe6bad0f5e67a4491c6b5e96ef41627b07f2118347ca5b388fb73cf97010db1befcb1d9797b50026d965cd8
    path: .yarn/plugins/@rnx-kit/yarn-plugin-external-workspaces.cjs
    spec: incubator/yarn-plugin-external-workspaces/dist/external-workspaces.cjs

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
