compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

externalWorkspacesOutputOnlyOnCommand: true

externalWorkspacesProvider: ../rnx-kit-workspaces.json

globalFolder: .yarn/berry

logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0069
    level: error

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  metro-config@*:
    dependencies:
      metro-transform-worker: ^0.81.0
  react-native@*:
    dependencies:
      "@react-native-community/cli": ^15.0.0
      "@react-native-community/cli-platform-android": ^15.0.0
      "@react-native-community/cli-platform-ios": ^15.0.0

plugins:
  - path: ../../.yarn/plugins/@rnx-kit/yarn-plugin-external-workspaces.cjs
    spec: ../../.yarn/plugins/@rnx-kit/yarn-plugin-external-workspaces.cjs

tsEnableAutoTypes: false

yarnPath: ../../.yarn/releases/yarn-4.6.0.cjs
