import type { Config } from "@react-native-community/cli-types";
import type { BundleArgs } from "@rnx-kit/metro-service";
import { bundle, loadMetroConfig } from "@rnx-kit/metro-service";
import type Bundle from "metro/src/shared/output/bundle";
import { deepEqual, ok } from "node:assert/strict";
import * as path from "node:path";
import { describe, it } from "node:test";

async function buildBundle(
  args: BundleArgs,
  ctx: Config,
  output: typeof Bundle
) {
  const config = await loadMetroConfig(ctx, {
    maxWorkers: args.maxWorkers,
    resetCache: args.resetCache,
    config: args.config,
  });

  return bundle(args, config, output);
}

describe("metro-serializer-esbuild", () => {
  const root = path.dirname(__dirname);

  async function bundle(
    entryFile: string,
    dev = false,
    sourcemapOutput: string | undefined = undefined
  ): Promise<string[]> {
    let result = "";
    await buildBundle(
      {
        entryFile,
        bundleEncoding: "utf8",
        bundleOutput: ".test-output.jsbundle",
        dev,
        platform: "ios",
        resetCache: true,
        resetGlobalCache: false,
        sourcemapOutput,
        sourcemapUseAbsolutePath: true,
        verbose: false,
      },
      {
        root,
        reactNativePath: path.dirname(
          require.resolve("react-native/package.json")
        ),
        dependencies: {},
        assets: [],
        commands: [],
        healthChecks: [],
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        platforms: { android: {}, ios: {} } as any,
        project: {},
        reactNativeVersion: "",
      },
      {
        ...require("metro/src/shared/output/bundle"),
        save: ({ code }) => {
          result = code;
        },
      }
    );
    return result.split("\n");
  }

  it("removes unused code", async () => {
    const result = await bundle("test/__fixtures__/direct.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/direct.ts",
      "  var direct_exports = {};",
      "  var init_direct = __esm({",
      '    "test/__fixtures__/direct.ts"() {',
      '      "use strict";',
      "      init_base();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_direct();",
      "})();",
      "",
    ]);
  });

  it("removes unused code (export *)", async () => {
    const result = await bundle("test/__fixtures__/exportAll.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/exportAllPublic.ts",
      "  var init_exportAllPublic = __esm({",
      '    "test/__fixtures__/exportAllPublic.ts"() {',
      '      "use strict";',
      "      init_base();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/exportAll.ts",
      "  var exportAll_exports = {};",
      "  var init_exportAll = __esm({",
      '    "test/__fixtures__/exportAll.ts"() {',
      '      "use strict";',
      "      init_exportAllPublic();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_exportAll();",
      "})();",
      "",
    ]);
  });

  it("removes unused code (nested export *)", async () => {
    const result = await bundle("test/__fixtures__/nestedExportAll.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/exportAllPublic.ts",
      "  var init_exportAllPublic = __esm({",
      '    "test/__fixtures__/exportAllPublic.ts"() {',
      '      "use strict";',
      "      init_base();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/nestedExportAllInternal.ts",
      "  var init_nestedExportAllInternal = __esm({",
      '    "test/__fixtures__/nestedExportAllInternal.ts"() {',
      '      "use strict";',
      "      init_exportAllPublic();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/nestedExportAllPublic.ts",
      "  var init_nestedExportAllPublic = __esm({",
      '    "test/__fixtures__/nestedExportAllPublic.ts"() {',
      '      "use strict";',
      "      init_nestedExportAllInternal();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/nestedExportAll.ts",
      "  var nestedExportAll_exports = {};",
      "  var init_nestedExportAll = __esm({",
      '    "test/__fixtures__/nestedExportAll.ts"() {',
      '      "use strict";',
      "      init_nestedExportAllPublic();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_nestedExportAll();",
      "})();",
      "",
    ]);
  });

  it("removes unused code (import *)", async () => {
    const result = await bundle("test/__fixtures__/importAll.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/importAll.ts",
      "  var importAll_exports = {};",
      "  var init_importAll = __esm({",
      '    "test/__fixtures__/importAll.ts"() {',
      '      "use strict";',
      "      init_base();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_importAll();",
      "})();",
      "",
    ]);
  });

  it("removes unused code (import * <- export *)", async () => {
    const result = await bundle("test/__fixtures__/importExportAll.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/exportAllPublic.ts",
      "  var init_exportAllPublic = __esm({",
      '    "test/__fixtures__/exportAllPublic.ts"() {',
      '      "use strict";',
      "      init_base();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/nestedExportAllInternal.ts",
      "  var init_nestedExportAllInternal = __esm({",
      '    "test/__fixtures__/nestedExportAllInternal.ts"() {',
      '      "use strict";',
      "      init_exportAllPublic();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/importExportAll.ts",
      "  var importExportAll_exports = {};",
      "  var init_importExportAll = __esm({",
      '    "test/__fixtures__/importExportAll.ts"() {',
      '      "use strict";',
      "      init_nestedExportAllInternal();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_importExportAll();",
      "})();",
      "",
    ]);
  });

  it("tree-shakes lodash-es", async () => {
    const _head = require.resolve("lodash-es/head.js", { paths: ["."] });
    const _lodash = require.resolve("lodash-es/lodash.js", { paths: ["."] });
    const result = await bundle("test/__fixtures__/lodash-es.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      `  // ${path.relative(root, _head).replaceAll("\\", "/")}`,
      "  function head(array) {",
      "    return array && array.length ? array[0] : void 0;",
      "  }",
      "  var head_default;",
      "  var init_head = __esm({",
      `    "${path.relative(root, _head).replaceAll("\\", "/")}"() {`,
      '      "use strict";',
      "      head_default = head;",
      "    }",
      "  });",
      "",
      `  // ${path.relative(root, _lodash).replaceAll("\\", "/")}`,
      "  var init_lodash = __esm({",
      `    "${path.relative(root, _lodash).replaceAll("\\", "/")}"() {`,
      '      "use strict";',
      "      init_head();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/lodash-es.ts",
      "  var lodash_es_exports = {};",
      "  var init_lodash_es = __esm({",
      '    "test/__fixtures__/lodash-es.ts"() {',
      '      "use strict";',
      "      init_lodash();",
      "      console.log(head_default([]));",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_lodash_es();",
      "})();",
      "",
    ]);
  });

  it("handles `sideEffects` array", async () => {
    const importResolve = (spec: string, parent = ".") => {
      const m = require.resolve(spec, { paths: [parent] });
      return path
        .relative(root, m)
        .replaceAll("\\", "/")
        .replace("/lib-commonjs/", "/lib/");
    };

    const fluentUtils = importResolve("@fluentui/utilities");
    const fluentSetVersion = importResolve(
      "@fluentui/set-version",
      path.join(root, fluentUtils)
    );

    const result = await bundle("test/__fixtures__/sideEffectsArray.ts");
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // ../../node_modules/.store/@fluentui-set-version-npm-8.2.12-8e95660752/package/lib/setVersion.js",
      "  function setVersion(packageName, packageVersion) {",
      '    if (typeof _win !== "undefined") {',
      "      var packages = _win.__packages__ = _win.__packages__ || {};",
      "      if (!packages[packageName] || !packagesCache[packageName]) {",
      "        packagesCache[packageName] = packageVersion;",
      "        var versions = packages[packageName] = packages[packageName] || [];",
      "        versions.push(packageVersion);",
      "      }",
      "    }",
      "  }",
      "  var packagesCache, _win;",
      "  var init_setVersion = __esm({",
      `    "${fluentSetVersion.replace("index.js", "setVersion.js")}"() {`,
      '      "use strict";',
      "      packagesCache = {};",
      "      _win = void 0;",
      "      try {",
      "        _win = window;",
      "      } catch (e) {",
      "      }",
      "    }",
      "  });",
      "",
      `  // ${fluentSetVersion}`,
      "  var init_lib = __esm({",
      `    "${fluentSetVersion}"() {`,
      '      "use strict";',
      "      init_setVersion();",
      '      setVersion("@fluentui/set-version", "6.0.0");',
      "    }",
      "  });",
      "",
      `  // ${fluentUtils.replace("index.js", "warn/warn.js")}`,
      "  function warn(message) {",
      "    if (_warningCallback && false) {",
      "      _warningCallback(message);",
      "    } else if (console && console.warn) {",
      "      console.warn(message);",
      "    }",
      "  }",
      "  var _warningCallback;",
      "  var init_warn = __esm({",
      `    "${fluentUtils.replace("index.js", "warn/warn.js")}"() {`,
      '      "use strict";',
      "      _warningCallback = void 0;",
      "    }",
      "  });",
      "",
      `  // ${fluentUtils.replace("index.js", "warn.js")}`,
      "  var init_warn2 = __esm({",
      `    "${fluentUtils.replace("index.js", "warn.js")}"() {`,
      '      "use strict";',
      "      init_warn();",
      "    }",
      "  });",
      "",
      `  // ${fluentUtils.replace("index.js", "version.js")}`,
      "  var init_version = __esm({",
      `    "${fluentUtils.replace("index.js", "version.js")}"() {`,
      '      "use strict";',
      "      init_lib();",
      '      setVersion("@fluentui/utilities", "8.13.9");',
      "    }",
      "  });",
      "",
      `  // ${fluentUtils}`,
      "  var init_lib2 = __esm({",
      `    "${fluentUtils}"() {`,
      '      "use strict";',
      "      init_warn2();",
      "      init_version();",
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/sideEffectsArray.ts",
      "  var sideEffectsArray_exports = {};",
      "  var init_sideEffectsArray = __esm({",
      '    "test/__fixtures__/sideEffectsArray.ts"() {',
      '      "use strict";',
      "      init_lib2();",
      '      warn("this should _not_ be removed");',
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_sideEffectsArray();",
      "})();",
      "",
    ]);
  });

  it("adds sourceMappingURL comment", async () => {
    const result = await bundle(
      "test/__fixtures__/direct.ts",
      false,
      ".test-output.jsbundle.map"
    );
    deepEqual(result, [
      "(() => {",
      "  var __defProp = Object.defineProperty;",
      "  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __hasOwnProp = Object.prototype.hasOwnProperty;",
      "  var __esm = (fn, res) => function __init() {",
      "    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;",
      "  };",
      "  var __copyProps = (to, from, except, desc) => {",
      '    if (from && typeof from === "object" || typeof from === "function")',
      "      for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {",
      "        key = keys[i];",
      "        if (!__hasOwnProp.call(to, key) && key !== except)",
      "          __defProp(to, key, { get: ((k) => from[k]).bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });",
      "      }",
      "    return to;",
      "  };",
      '  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);',
      "",
      "  // test/__fixtures__/base.ts",
      "  function app() {",
      '    "this should _not_ be removed";',
      "  }",
      "  var init_base = __esm({",
      '    "test/__fixtures__/base.ts"() {',
      '      "use strict";',
      "    }",
      "  });",
      "",
      "  // test/__fixtures__/direct.ts",
      "  var direct_exports = {};",
      "  var init_direct = __esm({",
      '    "test/__fixtures__/direct.ts"() {',
      '      "use strict";',
      "      init_base();",
      "      app();",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  init_direct();",
      "})();",
      "//# sourceMappingURL=.test-output.jsbundle.map",
      "",
    ]);
  });

  it("is disabled when `dev: true`", async () => {
    const result = await bundle("test/__fixtures__/direct.ts", true);
    ok(result[0].includes("__DEV__=true"));
  });

  it("preserves template literals", async () => {
    const result = await bundle("test/__fixtures__/templateLiterals.ts");
    deepEqual(result, [
      "(() => {",
      "  var __getOwnPropNames = Object.getOwnPropertyNames;",
      "  var __commonJS = (cb, mod) => function __require() {",
      "    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;",
      "  };",
      "",
      "  // test/__fixtures__/templateLiterals.ts",
      "  var require_templateLiterals = __commonJS({",
      '    "test/__fixtures__/templateLiterals.ts"() {',
      "      console.log`Hello`;",
      "    }",
      "  });",
      "",
      "  // virtual:metro:__rnx_prelude__",
      '  global = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : new Function("return this;")();',
      "  require_templateLiterals();",
      "})();",
      "",
    ]);
  });
});
