import { deepEqual } from "node:assert/strict";
import { describe, it } from "node:test";
import { loadLockfile } from "../src/yarn/lockfile.ts";

type NodeFileSystem = typeof import("node:fs");

function mockLockfile(result: string): NodeFileSystem {
  return { readFileSync: () => result } as unknown as NodeFileSystem;
}

describe("yarn:loadLockfile()", () => {
  it("parses classic 'yarn.lock'", () => {
    const lockfile = loadLockfile(
      "yarn.lock",
      mockLockfile(`
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@ampproject/remapping@^2.2.0":
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/@ampproject/remapping/-/remapping-2.3.0.tgz#ed441b6fa600072520ce18b43d2c8cc8caecc7f4"
  integrity sha512-30iZtAPgz+LTIYoeivqYo853f02jBYSd5uGnGpkFV0M3xOt9aN73erkgYAmZU43x4VfqcnLxW9Kpg3R5LC4YYw==
  dependencies:
    "@jridgewell/gen-mapping" "^0.3.5"
    "@jridgewell/trace-mapping" "^0.3.24"

"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13":
  version "7.26.2"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.26.2.tgz#4b5fab97d33338eff916235055f0ebc21e573a85"
  integrity sha512-RJlIHRueQgwWitWgF8OdFYGZX328Ax5BCemNGlqHfplnRT9ESi8JkFlvaVYbS+UubVY6dpv87Fs2u5M29iNFVQ==
  dependencies:
    "@babel/helper-validator-identifier" "^7.25.9"
    js-tokens "^4.0.0"
    picocolors "^1.0.0"

"@babel/code-frame@^7.16.0", "@babel/code-frame@^7.24.7":
  version "7.27.1"

"@rnx-kit/lint-lockfile@*":
  version "1.0.0"
`)
    );

    deepEqual(lockfile, {
      "@ampproject/remapping@^2.2.0": {
        package: "@ampproject/remapping",
        specifiers: ["^2.2.0"],
        resolution: "2.3.0",
      },
      "@babel/code-frame@^7.0.0, @babel/code-frame@^7.12.13": {
        package: "@babel/code-frame",
        specifiers: ["^7.0.0", "^7.12.13"],
        resolution: "7.26.2",
      },
      "@babel/code-frame@^7.16.0, @babel/code-frame@^7.24.7": {
        package: "@babel/code-frame",
        specifiers: ["^7.16.0", "^7.24.7"],
        resolution: "7.27.1",
      },
      "@rnx-kit/lint-lockfile@*": {
        package: "@rnx-kit/lint-lockfile",
        specifiers: ["*"],
        resolution: "1.0.0",
      },
    });
  });

  it("parses modern 'yarn.lock'", () => {
    const lockfile = loadLockfile(
      "yarn.lock",
      mockLockfile(`
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@ampproject/remapping@npm:^2.2.0":
  version: 2.2.0

"@babel/code-frame@npm:^7.0.0, @babel/code-frame@npm:^7.12.13":
  version: 7.27.1

"@babel/code-frame@npm:^7.24.7, @babel/code-frame@npm:^7.25.9":
  version: 7.27.4

"@rnx-kit/lint-lockfile@workspace:*":
  version: 0.0.0-use.local

"@rnx-kit/lint-lockfile@npm:1.0.0":
  version: 1.0.0
`)
    );

    deepEqual(lockfile, {
      "@ampproject/remapping@npm:^2.2.0": {
        package: "@ampproject/remapping",
        specifiers: ["npm:^2.2.0"],
        resolution: "2.2.0",
      },
      "@babel/code-frame@npm:^7.0.0, @babel/code-frame@npm:^7.12.13": {
        package: "@babel/code-frame",
        specifiers: ["npm:^7.0.0", "npm:^7.12.13"],
        resolution: "7.27.1",
      },
      "@babel/code-frame@npm:^7.24.7, @babel/code-frame@npm:^7.25.9": {
        package: "@babel/code-frame",
        specifiers: ["npm:^7.24.7", "npm:^7.25.9"],
        resolution: "7.27.4",
      },
      "@rnx-kit/lint-lockfile@workspace:*": {
        package: "@rnx-kit/lint-lockfile",
        specifiers: ["workspace:*"],
        resolution: "0.0.0-use.local",
      },
      "@rnx-kit/lint-lockfile@npm:1.0.0": {
        package: "@rnx-kit/lint-lockfile",
        specifiers: ["npm:1.0.0"],
        resolution: "1.0.0",
      },
    });
  });
});
