name: Setup the toolchain
description: Sets up the toolchain for the project
inputs:
  node-version:
    description: The version of Node to use
    type: string
    default: "20"
  node-cache:
    description: Cache global packages data
    type: string
    default: "yarn"
  jdk-version:
    description: The Java JDK version to use, if specified
    type: number
  platform:
    description: The target platform to set up toolchain for
    type: string
runs:
  using: composite
  steps:
    - name: Set up Ccache
      id: setup-ccache
      if: ${{ inputs.platform == 'ios' || inputs.platform == 'macos' }}
      run: |
        podfile_lock="packages/test-app/${{ inputs.platform }}/Podfile.lock"
        if [[ -f $(git rev-parse --show-toplevel)/.ccache/ccache.conf ]] && [[ -f "$podfile_lock" ]]; then
          if ! command -v ccache 1> /dev/null; then
            brew install ccache
          fi

          CCACHE_HOME=$(dirname $(dirname $(which ccache)))/opt/ccache

          echo "CCACHE_DIR=$(git rev-parse --show-toplevel)/.ccache" >> $GITHUB_ENV

          echo "CC=${CCACHE_HOME}/libexec/clang" >> $GITHUB_ENV
          echo "CXX=${CCACHE_HOME}/libexec/clang++" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV

          ccache --zero-stats 1> /dev/null

          clang --version > .clang-version
          input=$(find . -maxdepth 1 -name .clang-version -o -name .yarnrc.yml | sort)
          echo "cache-key=$(cat "$podfile_lock" $input | shasum -a 256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache }}
    - name: Set up JDK
      if: ${{ inputs.jdk-version != 0 }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.jdk-version }}
    - name: Cache /.ccache
      if: ${{ steps.setup-ccache.outputs.cache-key }}
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-ccache-${{ steps.setup-ccache.outputs.cache-key }}
