name: ci
on:
  push:
    branches:
      - trunk
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
  review:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Deduplicate packages
        run: yarn dedupe --check
      - name: Install
        run: yarn
      - name: Format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn format
          if [[ -n "$GITHUB_TOKEN" ]]; then
            git diff | yarn suggestion-bot
          fi
          git diff --exit-code
  release:
    permissions:
      contents: write # create releases (semantic-release)
      id-token: write # enable use of OIDC for trusted publishing
    needs: [build, review]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install
        run: yarn
      - name: Emit type declaration files
        run: yarn tsc
      - name: Update npm if <11.5.1
        if: ${{ github.ref == 'refs/heads/trunk' }}
        run: |
          if [[ "$(echo -e "11.5.1\n$(npm --version)" | sort --version-sort | head -n 1)" != "11.5.1" ]]; then
            npm install -g npm@11.5.2
          fi
          echo "npm version: $(npm --version)"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
