on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build-android:
    name: ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup the toolchain
        uses: ./.github/actions/setup-toolchain
        with:
          node-version: 14
          jdk-version: 11
      - name: Install package dependencies
        uses: ./.github/actions/yarn
      - name: Build Android app
        run: yarn run build:android
        working-directory: packages/${{ inputs.package }}
