on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      workspace-name:
        required: true
        type: string
      scheme-name:
        required: true
        type: string
jobs:
  build-ios:
    name: ${{ inputs.package }}
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup the toolchain
        uses: ./.github/actions/setup-toolchain
      - name: Install package dependencies
        run: |
          yarn
      - name: Setup Apple
        uses: ./.github/actions/setup-apple
        with:
          project-directory: ios
          working-directory: packages/${{ inputs.package }}
      - name: Build iOS app
        run: |
          yarn build:ios
        working-directory: packages/${{ inputs.package }}
