name: Build and Publish
on:
  push:
    branches: [main]
env:
  NODE_OPTIONS: "--disable-proto=delete"
jobs:
  build_and_publish:
    name: "Build and publish"
    permissions:
      contents: write # for GH releases and Git tags (Changesets)
      id-token: write # enable use of OIDC for trusted publishing
    if: ${{ github.repository == 'microsoft/rnx-kit' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Setup the toolchain
        uses: microsoft/react-native-test-app/.github/actions/setup-toolchain@2bd913d4bd2344039eec5500b9be0079fafd5b06 # 5.4.9
      - name: Install package dependencies
        run: |
          yarn
      - name: Build and test packages
        run: |
          yarn build:ci:all
      - name: Bundle packages
        run: |
          yarn bundle
      - name: Generate token for publishing
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write # for GH releases and Git tags (Changesets)
          permission-pull-requests: write # version PRs (Changesets)
      - name: Create release PR or publish to npm
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          # We cannot use the GHA generated tokens because we've disabled
          # creation of pull requests at the org level.
          github-token: ${{ steps.app-token.outputs.token }}
          publish-script: yarn publish:changesets
          version-script: yarn version:changesets
  website:
    name: "Publish website"
    permissions:
      contents: write # deploy to GitHub Pages (peaceiris/actions-gh-pages)
    needs: build_and_publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Install package dependencies
        run: |
          yarn
        working-directory: docsite
      - name: Build website
        run: |
          yarn build
        working-directory: docsite
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsite/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
