on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
jobs:
  build-android:
    name: ${{ inputs.package }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup the toolchain
        uses: ./.github/actions/setup-toolchain
        with:
          jdk-version: 11
      - name: Install package dependencies
        run: |
          yarn
      - name: Build Android app
        run: |
          yarn run build:android
        working-directory: packages/${{ inputs.package }}
