name: CI
on: pull_request
jobs:
  review:
    name: "Review"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 100
      - name: Deduplicate packages
        run: |
          npx yarn-deduplicate --list --fail
      - name: Cache /.yarn-offline-mirror
        uses: actions/cache@v2.1.6
        with:
          path: .yarn-offline-mirror
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install package dependencies
        run: yarn ci
      - name: Check for change files
        run: yarn run check
      - name: Format
        run: yarn format
      - name: Align dependencies
        run: yarn rnx-dep-check --write
      - name: Report changes
        run: git diff | GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn suggestion-bot
  build:
    name: "Build"
    strategy:
      matrix:
        node-version: [14, 15]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Cache /.yarn-offline-mirror
        uses: actions/cache@v2.1.6
        with:
          path: .yarn-offline-mirror
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install package dependencies
        run: yarn ci
      - name: Build and test packages
        run: yarn build:ci
      - name: Ensure READMEs are up-to-date
        if: ${{ matrix.node-version == 14 && matrix.os == 'ubuntu-latest' }}
        run: |
          yarn update-readme
          git diff | GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn suggestion-bot
      - name: Bundle packages
        run: yarn bundle:ci
      - name: Bundle test app with esbuild
        run: |
          yarn bundle+esbuild
        shell: bash
        working-directory: packages/test-app
  label:
    name: "Label"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v3.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
